# This workflow automates backporting of _pull requests_ (PR) to other
# branches when:
#
# 1. A PR is closed and has been merged (`closed` + `merged`).
# 2. The `backport` label is added to a PR.
#
# ### 🔧 What does the workflow do?
# - Generates an automatic backport of the closed or labeled PR.
# - Skips the `CHANGELOG.md` file when backporting.
# - Adds the `autocut` label to the backport PR.
# - Adds the `failed backport` label if the process fails.
#
# ### ✨ What is it for?
# This workflow is useful for keeping multiple branches synchronized with
# relevant changes without manual intervention.

name: Backport PRs
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # opensearch-trigger-bot installation ID
          installation_id: 22958780

      - name: Backport
        uses: VachaShah/backport@v2.2.0
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}
          head_template: backport/backport-<%= number %>-to-<%= base %>
          files_to_skip: "CHANGELOG.md"
          labels_template: "<%= JSON.stringify([...labels, 'autocut']) %>"
          failure_labels: "failed backport"
